# Site settings
title: Jessawynne
email: jessawynne@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

